name: server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  http: ^1.1.0
  mime: ^1.0.4
  shelf_static: ^1.1.2
  chopper: ^8.0.0
  json_annotation: ^4.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.3.3
  chopper_generator: ^8.0.0
  json_serializable: ^6.6.1
  swagger_dart_code_generator: ^3.0.1
