name: server
description: A Dart server application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.3
  shelf_static: ^1.1.2
  http: ^1.1.0
  mime: ^1.0.4
  sqlite3: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.2
  chopper: ^8.0.0
  json_annotation: ^4.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.0
  build_runner: ^2.3.3
  chopper_generator: ^8.0.0
  json_serializable: ^6.6.1
  swagger_dart_code_generator: ^3.0.1
